// Runs before `ng build` on Netlify.
// Reads SUPABASE_URL and SUPABASE_ANON_KEY from Netlify environment variables
// and writes them into the gitignored environment.production.ts file.
const fs = require('fs');
const path = require('path');

const url = process.env['SUPABASE_URL'];
const anonKey = process.env['SUPABASE_ANON_KEY'];

if (!url || !anonKey) {
  console.error('❌ Missing required environment variables: SUPABASE_URL and/or SUPABASE_ANON_KEY');
  process.exit(1);
}

const targetPath = path.join(__dirname, 'src', 'environments', 'environment.production.ts');

const content = `// Auto-generated by set-env.js at build time — do not edit or commit
export const environment = {
  production: true,
  supabase: {
    url: '${url}',
    anonKey: '${anonKey}'
  }
};
`;

fs.writeFileSync(targetPath, content);
console.log('✅ environment.production.ts written from Netlify env vars');
